engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
  eslint:
    enabled: true
  coffeelint:
    enabled: true
  rubocop:
    enabled: true

exclude_paths:
  - spec/**/*

ratings:
  paths:
    - lib/**
    - Gemfile
